### ISSUE TITLE
Gurobi solver?

### ISSUE THREAD

**Issue by brlcad** [bmpix/PolyVectorization#1]
Linking open source to a commercial solver is disappointing.  It makes it impossible to integrate and use your very interesting work.  Discovered your work at Siggraph and was excited to give it a try, but that dependency is a non-starter.

Are there plans to replace the solver with a different open source alternative?

**Comment by bmpix** [comment]
Thank you for the interest! It's an unnecessary dependency and easy to remove, but unfortunately, I never had time to fix it. It's on my todo list though!

**Comment by brlcad** [comment]
If you did, we would likely be interested in trying to integrate and use your code in a production and research context, investing effort to make it more robust if needed.  Glad to hear that it’s on your todo list and hope you can get to it sometime.  Thank you for your quick response!

**Comment by bmpix** [comment]
Fixed. Enjoy! If you need my input on integrating this code into somewhere, please let me know.
