### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by trouble-maker007** [bmpix/PolyVectorization#8]
[  2%] Automatic MOC and UIC for target polyvector_thing
[  2%] Built target polyvector_thing_autogen
[  5%] Building CXX object CMakeFiles/polyvector_thing.dir/src/main.cpp.o
/data/PolyVectorization/src/main.cpp: In function ‘int main(int, char**)’:
/data/PolyVectorization/src/main.cpp:311:2: error: ‘MainWindow’ was not declared in this scope
  MainWindow mw;
  ^
/data/PolyVectorization/src/main.cpp:311:13: error: expected ‘;’ before ‘mw’
  MainWindow mw;
             ^
/data/PolyVectorization/src/main.cpp:312:2: error: ‘mw’ was not declared in this scope
  mw.setImage(QString::fromStdString(filename), origMask);
  ^
/data/PolyVectorization/src/main.cpp:580:9: error: ‘a’ was not declared in this scope
  return a.exec();
         ^
make[2]: *** [CMakeFiles/polyvector_thing.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/polyvector_thing.dir/all] Error 2

**Comment by bmpix** [comment]
Most probably your Qt is either not installed or not configured properly, so MOC and UIC are not running. Please make sure if you type moc or uic in your command line, those tools get called. If you still have problems with compiling MainWindow.cpp, comment out the line 2 (#define WITH_GUI 1) in main.cpp. Then you'll compile the version without GUI, should be fine.

**Comment by trouble-maker007** [comment]
@bmpix thanks for the response, I fix the problem with delete all the code contain WITH_GUI, it will be ok
