### ISSUE TITLE
Request for optimized version

### ISSUE THREAD

**Issue by harpavatkeerti** [bmpix/PolyVectorization#9]
Hi, thanks for the really interesting work! 
I set up the code and got it running, and it gives pretty good stroke reconstruction. 

However, for a 1000x1000 image, even the setup without GUI is taking ~8-9 minutes on a linux machine with sufficient RAM. As mentioned in the readme, could you please provide the optimized version of the code. 

Thanks a lot!

**Comment by bmpix** [comment]
Thanks for your interest! Mind sharing the image so that I test it on my machine (under windows though)?

**Comment by harpavatkeerti** [comment]
@bmpix I was trying it on this image. 
![2](https://github.com/bmpix/PolyVectorization/assets/43930695/aa98c715-885e-4174-81eb-1cc26af63269)

**Comment by bmpix** [comment]
Takes roughly 30 seconds on my machine. Are you sure you're compiling with all optimizations, Release mode, like -O2 -s -DNDEBUG ?

**Comment by harpavatkeerti** [comment]
I just followed https://github.com/bmpix/PolyVectorization#building

Based on the logs, it seems the optimizations are set. 
<img width="1159" alt="image" src="https://github.com/bmpix/PolyVectorization/assets/43930695/dd9ac50c-ca6a-46a3-aee5-504c45de2bd4">

**Comment by harpavatkeerti** [comment]
I tried `cmake .. -D CMAKE_BUILD_TYPE=Release`, now it took just ~25 sec. 
With simply `cmake ..`, it doesn't do these optimizations, and takes a very long time.

Thanks!
